---
language: php

cache:
  directories:
  # - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

services:
# - mysql
# - postgresql

env:
  # global:
  # matrix:

matrix:
  fast_finish: true
  include:
  allow_failures:
  - php: nightly

before_install:
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- php -r "print_r(get_loaded_extensions(TRUE));";
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand;
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand;
    php -r "print_r(get_loaded_extensions(TRUE));";
  fi

install:
- composer initialize

script: true

after_script:
- ls --color
- ls -R --color bin config public src

- composer show
- $GOPATH/bin/ccat composer.json
- $GOPATH/bin/ccat config/bundles.php
- $GOPATH/bin/ccat config/routes.yaml
- $GOPATH/bin/ccat config/services.yaml
- $GOPATH/bin/ccat config/packages/framework.yaml
- $GOPATH/bin/ccat config/packages/routing.yaml
- $GOPATH/bin/ccat config/packages/dev/routing.yaml
- $GOPATH/bin/ccat config/packages/test/framework.yaml
- $GOPATH/bin/ccat src/Kernel.php
- php -s src/Kernel.php | elinks -force-html -dump-color-mode 4 -dump

- composer req --no-scripts sensiolabs/security-checker
- vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
